### ISSUE TITLE
Setting readonly still allows deleting chips

### ISSUE THREAD

**Issue by thomasdewaelheyns** [FlowingCode/ChipFieldAddon#34] opened 2021-02-04 14:43 UTC
Setting readonly on the chipfield still allows deleting chips through the close button when the field is setClosable(true) and with the backspace button.
The expected behaviour would be to hide/gray out and disable the close buttons when the field is put to readonly (directly or through the binder). Also the backspace button should not allow to remove chips.

**Comment by javier-godoy** [comment] 2021-02-04 17:53
Hello. Can you please post a small example? It seems to work as expected with

```
ChipField<String> chf = new ChipField<>("Read Only", "Mercury", "Venus", "Earth");
chf.setWidthFull();
chf.addSelectedItem("Mercury");
chf.addSelectedItem("Venus");
chf.setReadOnly(true);
chf.setClosable(true);
```
![chipfield-readonly](https://user-images.githubusercontent.com/11554739/106934321-be909100-66f8-11eb-9b63-e56c3474321f.gif)

**Comment by thomasdewaelheyns** [comment] 2021-02-04 19:03
Hi,

I don't have git installed on this laptop but with eclipse I made a simple example that shows the behaviour I described. I think it may be more related to going from editable to readonly. I think I might have found an additional issue while making this example. If you add a new element (so one that does not exist) from the field, it will show up when you click the "Show values" button. When you remove that chip again, and press the button again, the value you created will be still in the values. The same behaviour can be observed in your Data Provider example.

To demonstrate my issues, I downloaded the master and added a new tab to the "ChipFieldDemoView". The example class is called "ReadOnlyExample" in test in the com.flowingcode.vaadin.addons.chipfield.readonly package. Please let me know if you need further input.
[ChipFieldAddon_readonly.zip](https://github.com/FlowingCode/ChipFieldAddon/files/5927907/ChipFieldAddon_readonly.zip)

**Comment by javier-godoy** [comment] 2021-02-04 20:22
Thanks. Your example reproduces the issue, I'll investigate.

**Comment by javier-godoy** [comment] 2021-02-05 20:12
When adding a new item, the data provider is not updated with the new item, thus findItemByLabel will not retrieve it (#35).
Additionally, `setValue("Test")` (called by Binder) causes the creation of a new chip that isn't registeres as an additional item with the component (#36). Then, when the component is in readonly mode, it will allow deletion of such "unknown" items.

**Comment by thomasdewaelheyns** [comment] 2021-02-25 12:37
Are these issues being followed up on? I saw on a separate branch work was started but the last commit was 16 days ago. I'm asking because we are coming up on a test-release and I will have to substitute out the chipfield for something else otherwise while I would prefer to stick with your addon.

**Comment by javier-godoy** [comment] 2021-02-25 12:55
Yes, and I want to thank you very much for reporting those. They helped us a lot for improving the component. 

I had it in my backlog, but then I got other assignments and couldn't complete it. That branch fixes #35 and #36 which are the causes of this one. On the other hand I wasn't confident enough for a release, because the latest changes resulted in a very complicate internal logic (there are several actions, both client and server-side that result in chips being created or deleted). Then, I started with some integration tests using TestBench in order to verify there were no regressions. Would it be OK for you if we release it as an snapshot version while we wrap the changes?

**Comment by thomasdewaelheyns** [comment] 2021-02-25 13:04
Hey Javier,

No worries, I was not meaning to rush you. Please, take the time you need. Since this component is not yet used by us in anything in production I can test already a snapshot version and report any issues if I encounter any. I was just asking because the inability to delete chips was impeding on testing the general workflow.

**Comment by javier-godoy** [comment] 2021-02-25 14:21
@thomasdewaelheyns I fixes were merged into 2.4.0-SNAPSHOT, which has been deployed to https://maven.flowingcode.com/snapshots

**Comment by thomasdewaelheyns** [comment] 2021-02-25 15:17
@javier-godoy Thank you, I'll give it a go tomorrow and get back to you with my findings.

**Comment by thomasdewaelheyns** [comment] 2021-02-26 12:03
I tested the 2.4.0-SNAPSHOT quickly and so far all issues that I noticed seem resolved.
- Changing read only state now actually locks and unlocks deleting of items correctly. On or more items can still disappear for a split second when clicking the close button or backspacing but they are correctly returned into the UI and they are not being deleted in the back-end
- Chips can now correctly be deleted from the UI and they also are correctly removed from the back-end. Both for existing chips and newly created ones.
Next week I'm letting our research team and application specialists lose on the application and let them test more scenarios.

**Comment by javier-godoy** [comment] 2021-02-26 19:23
Thanks for the confirmation. I'm closing this issue since the component now preserves its value in read-only mode. I'll open a separate issue about improving the visual aspect, because there are several indicators that suggest the user can interact with the component (close button, blue underline, hand cursor).

**Closed by javier-godoy** 2021-02-26 19:23 UTC
Labels: bug
